2020-07-26T14:09:22|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autoRange'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 80, in update_display\n    self.imv.setImage((self.displayed_image), autoLevels=False, autoRange=self.settings.autoRange.val, levels=(self.settings.level_min.val, self.settings.level_max.val))\n', "AttributeError: 'LQCollection' object has no attribute 'autoRange'\n"]
2020-07-26T14:50:46|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'cnt'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 87, in update_display\n    self.displayed_image = self.draw_contours(image8bit_autoleveled,self.cnt,self.cx,self.cy)\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'cnt'\n"]
2020-07-26T15:14:47|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'int' object has no attribute 'val'\n"]
2020-07-26T15:14:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'numpy.uint16' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'numpy.uint16' object has no attribute 'val'\n"]
2020-07-26T15:14:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'numpy.uint16' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'numpy.uint16' object has no attribute 'val'\n"]
2020-07-26T15:14:57|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'numpy.uint16' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'numpy.uint16' object has no attribute 'val'\n"]
2020-07-26T15:14:58|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'numpy.uint16' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'numpy.uint16' object has no attribute 'val'\n"]
2020-07-26T15:15:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'numpy.uint16' object has no attribute 'val'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 86, in update_display\n    levels=(int(level_min.val), int(level_max.val))\n', "AttributeError: 'numpy.uint16' object has no attribute 'val'\n"]
2020-07-26T15:21:32|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:34|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:36|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:41|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:21:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'FakeCameraMeasurement' object has no attribute 'setting'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.setting.autolevels:\n', "AttributeError: 'FakeCameraMeasurement' object has no attribute 'setting'\n"]
2020-07-26T15:22:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:18|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:22|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:24|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:26|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:28|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:30|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:32|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:34|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:36|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:22:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:03|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:13|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:18|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:21|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:25|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:28|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T15:24:31|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'LQCollection' object has no attribute 'autolevels'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 85, in update_display\n    if self.settings.autolevels.val:\n', "AttributeError: 'LQCollection' object has no attribute 'autolevels'\n"]
2020-07-26T16:00:13|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:15|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:18|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:00:20|WARNING|LoggedQuantity|level_min read_from_hardware called when not connected to hardware
2020-07-26T16:07:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:07:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:08:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
2020-07-26T16:08:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 79, in update_display\n    level_min, level_max = self.get_levels(self.image, self.settings.auto_levels.val)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 127, in get_levels\n    self.settings.level_min.read_from_hardware()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 162, in read_from_hardware\n    self.update_value(new_val=val, update_hardware=False, send_signal=send_signal)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 223, in update_value\n    new_val = self.coerce_to_type(new_val)\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\logged_quantity.py", line 135, in coerce_to_type\n    return self.dtype(x)\n', "TypeError: int() argument must be a string, a bytes-like object or a number, not 'LoggedQuantity'\n"]
