2020-07-26T23:45:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:45:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:45:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:45:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:45:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:45:58|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:02|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:06|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:46:13|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:47|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:53|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:57|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:51:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:03|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:05|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:09|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
2020-07-26T23:52:13|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'ImageView' object has no attribute 'tVals'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 105, in update_display\n    #self.imv_external.setImage(self.displayed_image, autoLevels=False, autoRange=self.settings.auto_range.val, levels=(0,255))\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 308, in setImage\n    self.roiChanged()\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\pyqtgraph\\imageview\\ImageView.py", line 572, in roiChanged\n    self.roiCurve.setData(y=data, x=self.tVals)\n', "AttributeError: 'ImageView' object has no attribute 'tVals'\n"]
