2020-08-09T19:17:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:38|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:40|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:43|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:44|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:45|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:48|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:49|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:50|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:51|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:52|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:54|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:55|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:56|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:17:59|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:00|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:01|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:04|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:07|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:08|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:10|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:11|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:12|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:14|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:14|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:15|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:16|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:17|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:17|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:17|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:17|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:19|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:20|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:20|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:23|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
2020-08-09T19:18:24|ERROR|FakeCameraMeasurement|fake_camera_image Failed to update figure1: 'int' object is not iterable. ['Traceback (most recent call last):\n', '  File "C:\\Users\\Andrea Bassi\\anaconda3\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 108, in update_display\n    self.displayed_image = self.draw_contours(image8bit_normalized,self.cnt,self.cx,self.cy)\n', '  File "C:\\Users\\Andrea Bassi\\OneDrive - Politecnico di Milano\\Documenti\\PythonProjects\\BassiScopeFoundryMicroscopes\\Microscopes\\CellRecongnitionMicroscope\\FakeCameraMeasurement.py", line 203, in draw_contours\n    for indx, val in range(self.roi_num):\n', "TypeError: 'int' object is not iterable\n"]
